### ISSUE TITLE
Improve release workflow

### ISSUE THREAD

**Issue by mross-ua** [krazkidd/kdeck#28]
In #19, we built a proof-of-concept for a workflow to build and push releases (targeting Debian Bookworm) to GitHub. There is opportunity for improvements, automation, and integration with CMake. Some early ideas are:

### Tasks
- [ ] Allow targeting different Debian releases (namely, "stable" and "testing")
- [ ] Allow targeting different architectures (primarily 32-bit, 64-bit, and ARM?)
- [ ] Pass configuration type ("Release" or "Debug")
- [ ] Name the release package according to configuration (it's hard-coded now)
- [ ] Make more meaningful release notes (the workflow uses git's tag annotation; auto-generation is an option)
- [ ] Rename the workflow filename (`release.yaml` isn't helpful--this file targets Debian Bookworm)
- [ ] Set pre-release flag based on some property (version number? version suffix? tag annotation content? branch name?)
- [x] Allow manual triggering of the release workflow
- [ ] Add status badges to `README.md` for any new release workflows created

### Dependencies
- [x] #19
- [x] #18
- [x] #7
- [x] #67
