### ISSUE TITLE
Add Oat++ and implement generators for API client code

### ISSUE THREAD

**Issue by krazkidd** [krazkidd/kdeck#30]
Oat++ makes it easy to code up to an API spec[^1]. It is a header-only library and uses macros; they also provide examples and various modules.

[^1]: [trading-api-v2.0.json](https://github.com/user-attachments/files/15895000/trading-api-v2.0.json)

So far we have been using curlpp (libcURL wrapper) with Boost.JSON. All of these can be replaced by Oat++[^2].

[^2]: Oat++ provides a consistent high-level API while allowing a configurable low-level networking library. You can use the built-in support or libcURL or some other supported library (or provide your own `RequestExecutor` adapter).

This issue will not require the entire API to be implemented. It is enough to only convert what we have so far.

### Tasks
- [x] Convert Exchange API
- [x] Convert Portfolio API
- [x] Convert Login API
- [x] Update Docker/GitHub builds

### Dependencies
- [x] #36

---

<details><summary>Original description</summary>
<p>

Kalshi's REST API is [well-documented](https://trading-api.readme.io/) and they also provide a [Python client library](https://github.com/Kalshi/kalshi-python). I was even able to find an OpenAPI spec through a [poorly documented process](https://api.readme.dev/docs/installation) which is attached to this issue.

It should be possible to use the spec to generate some C++ classes to provide consistent low-level connection functionality, preferably using cURL or some other popular library for easy debugging. Note that a long-term goal is to support asynchronous (or multi-threaded) requests per #17 so that should be a supported modality.

</p>
</details>

**Comment by krazkidd** [comment]
A while ago I discovered a couple of free generators. One is provided by [Swagger](https://swagger.io/tools/swagger-codegen/) but only offers a C++ client using Microsoft's unmaintained [C++ REST SDK](https://github.com/microsoft/cpprestsdk) project (I have not verified this). There is also an [open-source fork](https://openapi-generator.tech/#try) offering some other options but none of them libcurl. It's worth seeing if any of these options are more modern.

**Comment by krazkidd** [comment]
I think we are going to go with [Oat++](https://oatpp.io/). It provides "Retrofit-like" client code generation (which I am familiar with) and support for WebSockets (#10), multi-threading (#17), and JSON.

I am just going to do #36 first for an easier switch.

**Comment by krazkidd** [comment]
Note that I converted the project to the vcpkg build and dependency-tracking system because Debian doesn't distribute Oat++.
