### ISSUE TITLE
User config saving/loading needs some work

### ISSUE THREAD

**Issue by krazkidd** [krazkidd/kdeck#54]
In #37, we added the ability to save user preferences to file but the solution is not robust enough to document or make widely known.

### Tasks
- [ ] Handle read/write errors (e.g. permissions, out of space, etc.)
- [ ] Handle (de-)serialization errors
- [ ] Fallback to defaults? Prompt user to use defaults?
- [ ] Notify user of errors
- [ ] Improve path-finding (directories don't create themselves...)
- [ ] TODO see [`Config.cpp`](https://github.com/krazkidd/kdeck/blob/main/src/config/Config.cpp) for other potential tasks
- [ ] Document in README
- [ ] Document in Help?

### Dependencies

- [x] #37
