### ISSUE TITLE
Add debug dialog for viewing web traffic

### ISSUE THREAD

**Issue by krazkidd** [krazkidd/kdeck#76]
I would like a dialog for viewing web requests/responses. This would just be a debugging tool and would be especially useful for the asynchronous WebSocket API.

wxWidgets may provide some kind of logging support. If not, maybe we could look into other options. So we can easily set up channels and subscriptions. The Kalshi WebSocket API (see #10) uses channels so we should be able to filter on those.

We could add a `Debug` menu item for accessing this kind of thing, so it's all mostly in one place.

### Tasks
- [ ] Add `Debug` menu
- [ ] Separate views for HTTP/RESTful traffic and WebSockets
- [ ] Add filter options for WebSocket API

### Dependencies

- [ ] #10
